remote_theme: samarsault/plainwhite-jekyll
# remote_theme: thelehhman/texture
title: Apx
author: GitHub User
email: ....
description: > # this means to ignore newlines until "show_exerpts:"
  Apx's Personal website.
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture
presentation: Presentation

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Apx
  tagline: Data Engineer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  navigation:
      - title: Home
        url: "https://agustinphx.github.io/"
      - title: My Work
        url: "/posts/my-work"
      - title: Resume
        url: "/posts/resume"


  # generate social links in footer
  social_links:
    linkedIn: in/apx
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up


# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
