title: "Agustín Philippeaux"
author: "Mix"
email: "agustinphx@gmail.com"
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: true

theme: minima

# Minima date format
sass:
  sass_dir: _sass

# Plugins
plugins:
  - jekyll-seo-tag

# Social links — solo se mostrarán si modificás el layout de minima
# o lo extendés con un plugin.
social_links:
  github: agustinphx
  linkedin: in/apx

# Site build options
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
