# title: Apx

# subtitle: Data Engineer

# logo: /assets/img/headshot_circle.png

# show_downloads: true

# remote_theme: thelehhman/texture

# theme: jekyll-theme-minimal

theme: texture


texture:
  title: Apx
  tagline: Data Engineer
  date_format: "%b %-d, %Y"

  social_links:
    linkedIn: in/apx # format: locale/username

texture:
  style: [yellow|red|black|blue|green|purple]
  showNav: true
  disqus_shortname: games
#  showPicker: [false|true] # show the texture selector(development purposes)

texture:
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"
