remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Apx
  tagline:  Data Engineer
  date_format: "%b %-d, %Y"
  search: true

portfolio_image:  "assets/profile_picture.png"

  social_links:
    github: https://github.com/agustinphx
    linkedIn: in/apx  # format: locale/username
