title: "Agustín Philippeaux"
  author: "Mix"
email: "agustinphx@gmail.com"
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: true

theme: minima

# Minima date format
sass:
  sass_dir: _sass
  
plainwhite:
  name: Agustín Philippeaux
  tagline: Data Engineer - Business and Systems degree
  date_format: "%b %-d, %Y"
sitemap: false # set to true to generate sitemap.xml content
search: false # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/profile_picture.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

# Plugins
plugins:
  - jekyll-seo-tag

# Social links — solo se mostrarán si modificás el layout de minima
# o lo extendés con un plugin.
social_links:
  github: agustinphx
  linkedin: in/apx

# Site build options
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
