remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Apx
  tagline:  Data Engineer
  date_format: "%b %-d, %Y"
  search: true

portfolio_image:  "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)

  social_links:
    github: https://github.com/agustinphx
    linkedIn: in/apx  # format: locale/username
